# Use postgres/example user/password credentials
version: '3.1'

services:

  auth_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ms_auth_psql
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
